const duasData = [
    {
      id: 'dua_1',
      title: 'Sleeping',
      arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
      english: 'Bismika Allahumma amutu wa ahya',
      translation: 'In Your name, O Allah, I die and I live.',
      reference: 'Sahih al-Bukhari, Hadith number 6312',
      image: require('../../../assets/icons/DuaDhikr/moon.png'),
    },
    {
      id: 'dua_2',
      title: 'Toilet',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
      english: 'Allahumma inni a’udhu bika minal khubthi wal khaba’ith',
      translation: 'O Allah, I seek refuge with You from evil and evildoers.',
      reference: 'Sahih al-Bukhari, Hadith number 142',
      image: require('../../../assets/icons/DuaDhikr/toilet.png'),
    },
    {
      id: 'dua_3',
      title: 'Ablution',
      arabic: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي وَوَسِّعْ لِي فِي دَارِي وَبَارِكْ لِي فِي رِزْقِي',
      english: 'Allahummaghfir li dhanbi, wassi’ li fi dari, wa barik li fi rizqi',
      translation: 'O Allah, forgive my sins, expand my home, and bless my sustenance.',
      reference: 'Sunan Ibn Majah, Hadith number 3833',
      image: require('../../../assets/icons/DuaDhikr/drops.png'),
    },
    {
      id: 'dua_4',
      title: 'Mosque',
      arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
      english: 'Allahummaf-tah li abwaba rahmatik',
      translation: 'O Allah, open the doors of Your mercy for me.',
      reference: 'Sahih Muslim, Hadith number 713',
      image: require('../../../assets/icons/DuaDhikr/mosque.png'),
    },
    {
      id: 'dua_5',
      title: 'Food',
      arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ',
      english: 'Allahumma barik lana fima razaqtana waqina ‘adhaban-nar',
      translation: 'O Allah, bless the food You have provided us and save us from the punishment of the Fire.',
      reference: 'Sunan Abu Dawood, Hadith number 3763',
      image: require('../../../assets/icons/DuaDhikr/food.png'),
    },
    {
      id: 'dua_6',
      title: 'Travel',
      arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ',
      english: 'Subhanal-ladhi sakh-khara lana hadha wama kunna lahu muqrinin wa inna ila rabbina lamunqalibun',
      translation: 'Glory to Him who has subjected this to us, and we could not have done it by ourselves. And to our Lord, we shall surely return.',
      reference: 'Surah Az-Zukhruf (43:13-14)',
      image: require('../../../assets/icons/DuaDhikr/travel.png'),
    },
  ];
  export default duasData;